"""empty message

Revision ID: 10d3f908e149
Revises: 5b2c2edfe397
Create Date: 2018-04-20 20:46:00.075971

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "10d3f908e149"
down_revision = "5b2c2edfe397"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_title"), "post", ["title"], unique=False)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_title"), table_name="post")
    op.drop_table("post")


# ### end Alembic commands ###
