"""empty message

Revision ID: 69dde86c90c0
Revises: dd953ec5d60b
Create Date: 2018-04-25 18:13:31.508213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69dde86c90c0"
down_revision = "dd953ec5d60b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"]),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")


# ### end Alembic commands ###
