"""empty message

Revision ID: a783e7fb831e
Revises: b429f1c4ee70
Create Date: 2018-04-18 15:12:59.356774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a783e7fb831e'
down_revision = 'b429f1c4ee70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_since', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'location')
    op.drop_column('user', 'last_since')
    op.drop_column('user', 'age')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
