"""empty message

Revision ID: d19184a0a0d9
Revises: 1bce97782e19
Create Date: 2018-04-18 23:14:00.498562

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d19184a0a0d9"
down_revision = "1bce97782e19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_role_name", table_name="role")
    op.drop_table("role")
    op.drop_table("roles")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("role_id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_role_name", "role", ["name"], unique=False)


# ### end Alembic commands ###
